application: webflipflapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/
  static_dir: static

- url: /blah
  script: blah.application

- url: /oauth2callback
  script: main.appoauth

- url: /.*
  script: main.appgae

