application: webflipflapp
version: 1-4-1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/
  static_dir: static
  secure: always

- url: /oauth2callback
  script: main.appoauth
  secure: always

- url: /.*
  script: main.appgae
  secure: always

libraries:
- name: webob
  version: "1.2.3"

