runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/
  static_dir: static
  secure: always

- url: /oauth2callback
  script: main.appoauth
  secure: always

- url: /.*
  script: main.appgae
  secure: always

libraries:
- name: ssl
  version: latest
